# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfWorkers 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#
#
#
/gun/particle proton
/gun/energy 5.2 MeV
#
# 10^12
/run/beamOn 1000000000
#/run/beamOn 10000
